services:
  - type: web
    name: ai-tutor-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
